import logging
from datetime import datetime, timezone
from pathlib import Path

from iwa_rnaseq_counter.models.matrix import MatrixSpec
from iwa_rnaseq_counter.models.execution_run import ExecutionRunSpec
from iwa_rnaseq_counter.models.execution_step import ExecutionStepRecord
from iwa_rnaseq_counter.io.write_matrix_spec import write_matrix_spec
from iwa_rnaseq_counter.io.write_execution_run_spec import write_execution_run_spec
from iwa_rnaseq_counter.builders.execution_run_builder import build_execution_run_spec_for_success

logger = logging.getLogger(__name__)


def _canonical_run_context_from_summary(run_summary: dict) -> dict:
    """
    v0.8.2 canonical run context.
    新規コードはこのキー群を優先して読む。
    """
    return {
        "quantifier": run_summary.get("quantifier", "unknown"),
        "quantifier_version": run_summary.get("quantifier_version", "unknown"),
        "aggregation_input_kind": run_summary.get(
            "aggregation_input_kind",
            "transcript_quant",
        ),
        "quantifier_index_path": run_summary.get("quantifier_index_path"),
        "tx2gene_path": run_summary.get("tx2gene_path"),
        "annotation_gtf_path": run_summary.get("annotation_gtf_path"),
    }

def build_matrix_spec_from_gui_result(
    run_dir: Path,
    run_summary: dict,
    matrix_rel_path: str = "results/gene_numreads.csv",
    feature_annotation_path: str | None = None,
    feature_annotation_available: bool = False
) -> MatrixSpec:
    """
    Builds a MatrixSpec for the aggregated count matrix generated by the GUI.
    """
    matrix_abs_path = (run_dir / matrix_rel_path).resolve()
    
    # GUI doesn't have explicit Assay IDs, synthesize them from Sample IDs
    sample_ids = run_summary.get("sample_ids_success", [])
    assay_ids = [f"ASSAY_{sid}" for sid in sample_ids]
    
    run_name = run_summary.get("run_name", "UNKNOWN_RUN")
    matrix_id = f"MAT_{run_name}"
    
    canonical_run_context = _canonical_run_context_from_summary(run_summary)

    metadata = {
        "producer_app": "iwa_rnaseq_counter",
        "producer_version": "0.3.5",
        "run_origin": "gui",
        "gui_mode": run_summary.get("discovery_mode", "unknown"),
        "sample_ids": sample_ids,
        "input_dir": run_summary.get("input_dir", ""),
        "feature_id_system_inferred": False,
        "feature_annotation_available": feature_annotation_available,
        **canonical_run_context,
    }
    
    # Include output refs from GUI if needed
    
    return MatrixSpec(
        schema_name="MatrixSpec",
        schema_version="0.1.0",
        matrix_id=matrix_id,
        matrix_scope="analysis",
        matrix_kind="count_matrix",
        feature_type="gene",
        value_type="integer",
        normalization="raw",
        feature_id_system="ensembl_gene_id",
        sample_axis="specimen",
        matrix_path=str(matrix_abs_path),
        feature_annotation_path=feature_annotation_path,
        source_assay_ids=assay_ids,
        source_specimen_ids=sample_ids,
        source_subject_ids=sample_ids,
        metadata=metadata,
        overlay={}
    )


def build_execution_run_spec_from_gui_result(
    run_dir: Path,
    run_summary: dict,
    matrix_spec: MatrixSpec,
    started_at: str,
    log_rel_path: str = "logs/run.log"
) -> ExecutionRunSpec:
    """
    Builds an ExecutionRunSpec for the entire GUI run.
    """
    log_abs_path = (run_dir / log_rel_path).resolve()
    run_name = run_summary.get("run_name", f"RUN_GUI_{datetime.now().strftime('%Y%m%d_%H%M%S')}")
    
    canonical_run_context = _canonical_run_context_from_summary(run_summary)

    parameters = {
        "run_origin": "gui",
        "input_mode": run_summary.get("discovery_mode", "unknown"),
        "input_dir": str(run_summary.get("input_dir", "")),
        "sample_count": run_summary.get("sample_count", 0),
        "success_count": run_summary.get("success_count", 0),
        "strandedness_mode": (
            run_summary.get("strandedness", {}).get("mode", "Auto-detect")
            if isinstance(run_summary.get("strandedness"), dict)
            else "Auto-detect"
        ),
        "threads": run_summary.get("threads", 4),
        **canonical_run_context,
    }
    
    sample_ids = run_summary.get("sample_ids_success", [])
    assay_ids = [f"ASSAY_{sid}" for sid in sample_ids]
    
    status = "completed" if run_summary.get("failure_count", 0) == 0 else "completed_with_errors"
    
    return build_execution_run_spec_for_success(
        run_id=run_name,
        app_version="0.3.5",
        started_at=started_at,
        input_refs=assay_ids,
        output_refs=[matrix_spec.matrix_id],
        parameters=parameters,
        execution_backend="local-gui",
        log_path=str(log_abs_path),
        status=status,
        preprocessing_steps={
            "qc": ExecutionStepRecord(enabled=False, status="not_run"),
            "trimming": ExecutionStepRecord(enabled=False, status="not_run"),
        },
        metadata={
            "status_detail": status
        }
    )

def write_gui_supporting_inputs(
    run_dir: Path,
    run_summary: dict,
    matrix_rel_path: str = "results/gene_numreads.csv",
    log_rel_path: str = "logs/run.log",
    started_at: str | None = None,
    feature_annotation_path: str | None = None,
    feature_annotation_available: bool = False
) -> None:
    """
    Main entrypoint for GUI spec generation.
    Generates and saves specs mapping GUI results to the standard models.
    """
    if started_at is None:
        started_at = datetime.now(timezone.utc).astimezone().isoformat()
        
    specs_dir = run_dir / "specs"
    specs_dir.mkdir(parents=True, exist_ok=True)
    
    matrix_spec = build_matrix_spec_from_gui_result(
        run_dir, 
        run_summary, 
        matrix_rel_path,
        feature_annotation_path=feature_annotation_path,
        feature_annotation_available=feature_annotation_available
    )
    write_matrix_spec(matrix_spec, specs_dir / "matrix.spec.json")
    
    exec_run_spec = build_execution_run_spec_from_gui_result(run_dir, run_summary, matrix_spec, started_at, log_rel_path)
    write_execution_run_spec(exec_run_spec, specs_dir / "execution-run.spec.json")
    
    logger.info("Successfully generated GUI adapter specs in specs/ folder")
